# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Time2Goal' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Time2Goal
  pod 'GoogleMobileVision/FaceDetector'
  pod 'GoogleMobileVision/MVDataOutput'


end

target 'Time2Goal-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Time2Goal-tvOS

end
